### PR TITLE
[aws-cli] Various refactors to existing code

### PR DESCRIPTION
**Pull request by MindNumbing**
Add inspec.lock to .gitignore
Update README.md to latest binary format
Update inspec to latest version

Major changes to attributes.yml / controls
  Added lists of binaries to test / ignore
  Added tests to check the binaries exist and are executable
  Added tests to check the version command works

Signed-off-by: Steven Marshall <SMarshall@chef.io>

### CODE REVIEW

**Review by skpaterson — APPROVED** [review]
💯 thanks @MindNumbing

**Comment by skpaterson** [comment]
Tests failed unfortunately though!

**Comment by MindNumbing** [comment]
Forgot to remove my local testing code 👎 

EDIT - Looks like I have other problems 😢

**Review by skpaterson — APPROVED** [review]
👍

**Pull request merged**
